### ISSUE TITLE
New player 1.6.1 breaking seek

### ISSUE THREAD

**Issue by jseward311** [brion/ogv.js#528]
After pulling in the new player I am receiving the following error which breaks seek. 

TypeError: B[r] is undefined

flush
http://localhost:81/Scripts/Lib/ogvjs-uptivity/ogv.js:56:12911
AudioFeeder.prototype.flush
http://localhost:81/Scripts/Lib/ogvjs-uptivity/ogv.js:41:35794
prepForSeek
http://localhost:81/Scripts/Lib/ogvjs-uptivity/ogv.js:18:30985
_seek
http://localhost:81/Scripts/Lib/ogvjs-uptivity/ogv.js:18:31093
setCurrentTime
http://localhost:81/Scripts/Lib/ogvjs-uptivity/ogv.js:18:19523

Last release the media source was changed to except a stream of media. 
Not sure if this is the reason for the break here or not yet. 
Still looking into this.

**Comment by samfoucart** [comment]
I am getting the error: 

>TypeError: Cannot read property 'out_time' of undefined
 >    at Object.flush (d:\html5playerparea\webplayerjs\scripts\lib\ogvjs-uptivity\ogv.js:56:12920)
 >    at AudioFeeder.flush (d:\html5playerparea\webplayerjs\scripts\lib\ogvjs-uptivity\ogv.js:41:35814)
 >    at prepForSeek (d:\html5playerparea\webplayerjs\scripts\lib\ogvjs-uptivity\ogv.js:18:31689)
 >    at HTMLUnknownElement._seek (d:\html5playerparea\webplayerjs\scripts\lib\ogvjs-uptivity\ogv.js:18:31782)
 >    at HTMLUnknownElement.setCurrentTime (d:\html5playerparea\webplayerjs\scripts\lib\ogvjs-uptivity\ogv.js:18:19949)
 >    at d:\html5playerparea\webplayerjs\scripts\app\viewmodels\playerviewmodel.js:50:37
 >    at PlayerViewModel.props.set (d:\html5playerparea\webplayerjs\scripts\app\viewmodels\viewmodel.js:28:22)
 >    at HTMLDivElement.private.waveSlider.onMouseDrag (d:\html5playerparea\webplayerjs\webplayer.js:190:50)
 >    at Object.private.mouseSetPosition (d:\html5playerparea\webplayerjs\scripts\app\views\wavesliderview.js:622:25)
 >    at HTMLCanvasElement.<anonymous> (d:\html5playerparea\webplayerjs\scripts\app\views\wavesliderview.js:63:22)

It's referenced here in the ogv.js:
![image](https://user-images.githubusercontent.com/43978545/60920574-7f713400-a266-11e9-9530-9e66618961c6.png)


I think the issue comes from [audio-tempo-changer.js](https://github.com/velochy/audio-tempo-changer.js/blob/master/src/audio_tempo_changer.js#L112) on line 112.
This line says:
 `while(out_time<=changes[ci].out_time && ci>=0) { changes.pop(); ci--; }`

**Comment by brion** [comment]
Hmm, I'm not able to reproduce this so far. Do you have a sample file and a reliable way to reproduce it in code or through UI?

For instance this does not present any problems for me, entered as one line in console (using an audio webm file):

```
q = new OGVPlayer();
q.src = 'https://upload.wikimedia.org/wikipedia/commons/4/41/Zarna.webm';
q.load();
q.currentTime = 75.234;
q.play();
```

It seeks and plays without error.

**Comment by brion** [comment]
@velochy I haven't been able to repro this issue yet but I think it's caused when the AudioFeeder is initialized inside OGVPlayer but has nothing queued up yet when we flush things out for a seek. Does the suggested fix in above comments sound right to you (changing order to short-circuit the `ci >= 0`) or should it be slightly different?

**Comment by brion** [comment]
(I _think_ the 0 entry in `changes` should be left in place, and it should actually be `ci > 0` here.)

**Comment by samfoucart** [comment]
I just tried modifying the ogv.js file and: 
![image](https://user-images.githubusercontent.com/43978545/60974747-9eb8a180-a2f8-11e9-9033-f7dde6e1be52.png)

and: 
![image](https://user-images.githubusercontent.com/43978545/60974811-c4de4180-a2f8-11e9-9ae9-df4a14ab70a7.png)

both fixed our issue.

So in the tempo changer, 
`ci >= 0 && out_time <= changes[ci].out_time` 
and 
`out_time <= changes[ci].out_time && ci > 0`
should both work.

**Comment by velochy** [comment]
@samfoucart can you make it into a PR (and bump the minor version with it)? Im on a holiday without my work laptop, but i should be able to approve and merge the PR and update npm from my phone

**Comment by velochy** [comment]
@samfoucart Thank you for the fix.
Unfortunately, npm publish can not be done from phone as i hoped 
@brionv I gave you access to the npm package. can you maybe publish it?

**Comment by andreyrd** [comment]
Can this update get published in 1.6.2 or something? Or will 1.7.x be released soon?

**Comment by brion** [comment]
Sorry, forgot about this -- I have a 1.7 release coming up, just got caught up on some last-minute threading issues.
